services:
  - type: web
    name: crm-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-red-shadow-ahhgmkdb-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_7TpgUNEzZD4w
      - key: SERVER_PORT
        value: 8080
      - key: JWT_SECRET
        value: gCvrq3RGAZuhYcOesnRs3uJ6vXC+rNnTLX8SUWBO12qwb6hoxPmNleC9NGoc3sgtrVKVzSh5Ivg0l+RHATK2Ug==
      - key: JWT_EXPIRATION
        value: 3600000
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: CLOUDINARY_CLOUD_NAME
        value: dhy4osny1
      - key: CLOUDINARY_API_KEY
        value: 865596957416389
      - key: CLOUDINARY_API_SECRET
        value: 97oWr1Kqow8ODafY_fizJCeXXG4
