version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - crm-mysql-data:/var/lib/mysql

volumes:
  crm-mysql-data:
